[project]
name = "m4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.29.1",
    "mcp[cli]>=1.9.0",
    "rich>=14.0.0",
    "setuptools>=80.7.1",
]
